ALTER TABLE T_USER DROP FOREIGN KEY FK_T_USER_ACCOUNT_ID
ALTER TABLE T_TRANSACTION DROP FOREIGN KEY FK_T_TRANSACTION_ACCOUNT_ID
ALTER TABLE T_TRANSACTION DROP FOREIGN KEY FK_T_TRANSACTION_STATEMENT_ID
ALTER TABLE T_IDEA DROP FOREIGN KEY FK_T_IDEA_USER_ID
ALTER TABLE T_SHORTSELL DROP FOREIGN KEY FK_T_SHORTSELL_ACCOUNT_ID
ALTER TABLE T_SHORTSELL DROP FOREIGN KEY FK_T_SHORTSELL_TRANSACTION_ID
ALTER TABLE T_STATEMENTSTAKE DROP FOREIGN KEY FK_T_STATEMENTSTAKE_ACCOUNT_ID
ALTER TABLE T_STATEMENTSTAKE DROP FOREIGN KEY FK_T_STATEMENTSTAKE_STATEMENT_ID
ALTER TABLE T_ACCOUNT_T_IDEA DROP FOREIGN KEY FK_T_ACCOUNT_T_IDEA_ideas_ID
ALTER TABLE T_ACCOUNT_T_IDEA DROP FOREIGN KEY FK_T_ACCOUNT_T_IDEA_Account_ID
DROP TABLE T_USER
DROP TABLE T_TRANSACTION
DROP TABLE t_statement
DROP TABLE T_ACCOUNT
DROP TABLE T_IDEA
DROP TABLE T_SHORTSELL
DROP TABLE T_STATEMENTSTAKE
DROP TABLE T_ACCOUNT_T_IDEA
