[   { "username": "gosho-sexa", "cointels": 123,"total":400 },
    { "username": "kiro", "cointels": 800, "total": 100 },
    { "username": "semo", "cointels": 900, "total": 999 },
    { "username": "strahil", "cointels": 1000, "total": 1 },
    { "username": "asencho", "cointels": 333, "total": 1000 },
    { "username": "pavel", "cointels": 1, "total": 10 },
    { "username": "mitaka", "cointels": 3, "total": 56 },
    { "username": "gosho-sexa", "cointels": 123, "total": 560 },
    { "username": "kiro", "cointels": 800, "total": 431 },
    { "username": "semo", "cointels": 900, "total": 567 },
    { "username": "strahil", "cointels": 1000, "total": 1876 },
    { "username": "asencho", "cointels": 333, "total": 341 },
    { "username": "pavel", "cointels": 1, "total": 542 },
    { "username": "mitaka", "cointels": 3, "total": 876 }]

